<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7A005MA" failures="1" tests="6" name="Default test" time="20.243" errors="0" timestamp="28 Oct 2021 07:33:46 GMT">
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC01_Login_Empty_Filed" time="0.337"/>
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC02_Login_Invalid_Email" time="0.364">
    <failure type="java.lang.AssertionError" message="expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]">
      <![CDATA[java.lang.AssertionError: expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webdriver.Topic_Xpath_Technical_01.TC02_Login_Invalid_Email(Topic_Xpath_Technical_01.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_Login_Invalid_Email -->
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC03_Login_Incorrrect_confirm_email" time="0.363"/>
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC04_Login_Pass_Lessthan_6" time="0.359"/>
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC05_Login_Incorrrect_confirm_Pass" time="0.363"/>
  <testcase classname="webdriver.Topic_Xpath_Technical_01" name="TC06_Login_Invalid_Phone" time="0.83"/>
</testsuite> <!-- Default test -->
