<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-JMK0BG4" name="webdriver.Topic_Xpath_Technical_01" tests="6" failures="1" timestamp="29 Oct 2021 12:59:39 GMT" time="14.094" errors="0">
  <testcase name="TC02_Login_Invalid_Email" time="2.557" classname="webdriver.Topic_Xpath_Technical_01">
    <failure type="java.lang.AssertionError" message="expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]">
      <![CDATA[java.lang.AssertionError: expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webdriver.Topic_Xpath_Technical_01.TC02_Login_Invalid_Email(Topic_Xpath_Technical_01.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_Login_Invalid_Email -->
  <testcase name="TC04_Login_Pass_Lessthan_6" time="2.195" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC06_Login_Invalid_Phone" time="2.716" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC01_Login_Empty_Filed" time="2.530" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC03_Login_Incorrrect_confirm_email" time="2.012" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC05_Login_Incorrrect_confirm_Pass" time="2.084" classname="webdriver.Topic_Xpath_Technical_01"/>
</testsuite> <!-- webdriver.Topic_Xpath_Technical_01 -->
