<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7A005MA" name="webdriver.Topic_Xpath_Technical_01" tests="6" failures="1" timestamp="26 Oct 2021 08:57:48 GMT" time="19.363" errors="0">
  <testcase name="TC04_Login_Pass_Lessthan_6" time="0.509" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC06_Login_Invalid_Phone" time="1.528" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC02_Login_Invalid_Email" time="1.605" classname="webdriver.Topic_Xpath_Technical_01">
    <failure type="java.lang.AssertionError" message="expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]">
      <![CDATA[java.lang.AssertionError: expected [Vui lòng nhập email hợp] but found [Vui lòng nhập email hợp lệ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at webdriver.Topic_Xpath_Technical_01.TC02_Login_Invalid_Email(Topic_Xpath_Technical_01.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_Login_Invalid_Email -->
  <testcase name="TC03_Login_Incorrrect_confirm_email" time="3.146" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC01_Login_Empty_Filed" time="1.386" classname="webdriver.Topic_Xpath_Technical_01"/>
  <testcase name="TC05_Login_Incorrrect_confirm_Pass" time="11.189" classname="webdriver.Topic_Xpath_Technical_01"/>
</testsuite> <!-- webdriver.Topic_Xpath_Technical_01 -->
